"""add_occ_symbol

Revision ID: 002
Revises: 001
Create Date: 2026-07-12 20:01:40.851752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('occ_symbol', sa.String(), nullable=True))
    # ### end Alembic commands ###

    # Data patch to backfill existing positions with OCC symbols
    from datetime import datetime
    connection = op.get_bind()
    rows = connection.execute(
        sa.text("SELECT id, symbol, expiration_date, call_put, strike_price FROM positions")
    ).fetchall()

    for row in rows:
        pos_id, symbol, expiration_date, call_put, strike_price = row
        if symbol and expiration_date and call_put and strike_price is not None:
            # Parse datetime defensively from SQLite string
            dt = None
            date_str = str(expiration_date).split('T')[0].split('.')[0].strip()
            for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%d", "%Y-%m-%d %H:%M:%S.%f"):
                try:
                    dt = datetime.strptime(date_str, fmt)
                    break
                except ValueError:
                    continue
            
            if dt:
                ticker = symbol.upper()
                exp_str = dt.strftime("%y%m%d")
                cp_char = call_put[0].upper()
                strike_str = f"{int(strike_price * 1000):08d}"
                occ = f"{ticker}{exp_str}{cp_char}{strike_str}"
                
                connection.execute(
                    sa.text("UPDATE positions SET occ_symbol = :occ WHERE id = :id"),
                    {"occ": occ, "id": pos_id}
                )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'occ_symbol')
    # ### end Alembic commands ###
